@startuml
class "Proyecto" {
    Nombre: "1 Texto"
    Fecha de inicio: 1 Tiempo
    Fecha de fin: 0..1 Tiempo
}
class "Miembros del Equipo"{
   Nombre: 1 Texto
   Apellidos: 1 Texto
   Rol: 0..* Texto

}
class "Lugar de Actuacion" {
    Nombre: 0..* Texto
    Coordenada X: 1 Número
    Coordenada Y: 1 Número

}
"Miembros del Equipo" "1..*" -- "0..*" "Proyecto" : Participa en
"Proyecto" "0..*" -- "0..*" "Lugar de Actuacion" : Tiene Lugar en 
@enduml